// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Anklerollfabrik_BODY

/************************************************************
 Anklerollfabrik class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Anklerollfabrik.h"

// Derived includes directives
#include "Robotersimulation/Naosimulation/Koerperteil.h"
#include "Robotersimulation/Naosimulation/Welt.h"

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @param *koerper1 
 * @param *koerper2 
 * @param *welt 
 * @param seite 
 * @return  
 */
ODEGelenk * Anklerollfabrik::getGelenk(Koerperteil /*in*/*koerper1,
		Koerperteil /*in*/*koerper2, Welt /*in*/*welt, char /*in*/seite) {

	ODEGelenk *gelenk = new ODEGelenk();

	gelenk->erzeugeGelenk(koerper1, koerper2, welt);

	if (seite == 'l') gelenk->setAnker(bein_x, 0, knoechel_y);
	else gelenk->setAnker(-bein_x, 0, knoechel_y);

	gelenk->setAchse(0, 1, 0);
	gelenk->setMinWinkel(-44.06);
	gelenk->setMaxWinkel(22.79);

	return gelenk;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Anklerollfabrik class body
 ************************************************************/
