// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROBOTERSIMULATION_NAOSIMULATION_ANKLEPITCHFABRIK_H
#define ROBOTERSIMULATION_NAOSIMULATION_ANKLEPITCHFABRIK_H

/************************************************************
 Anklepitchfabrik class header
 ************************************************************/

#include "Robotersimulation/Naosimulation/Pkg_Naosimulation.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Robotersimulation/Naosimulation/Gelenkfabrik.h"
#include "Robotersimulation/Naosimulation/Gemeinsames.h"
#include "Robotersimulation/Pkg_Robotersimulation.h"

namespace Robotersimulation {
namespace Naosimulation {

/************************************************************/
/**
 * 
 */
class Anklepitchfabrik: public Gelenkfabrik {
public:

	/**
	 * 
	 * @param koerper1 
	 * @param koerper2 
	 * @param welt 
	 * @param seite 
	 * @return  
	 */
	ODEGelenk * getGelenk(Koerperteil * /*in*/koerper1,
			Koerperteil * /*in*/koerper2, Welt * /*in*/welt, char /*in*/seite);

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Anklepitchfabrik class header
 ************************************************************/

#endif
