// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROBOTERSIMULATION_NAOSIMULATION_KOERPERTEIL_H
#define ROBOTERSIMULATION_NAOSIMULATION_KOERPERTEIL_H

/************************************************************
 Koerperteil class header
 ************************************************************/

#include "Robotersimulation/Naosimulation/Pkg_Naosimulation.h"
#include "Robotersimulation/Naosimulation/Welt.h"
#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Robotersimulation/Pkg_Robotersimulation.h"

namespace Robotersimulation {
namespace Naosimulation {

/************************************************************/
/**
 * 
 */
class Koerperteil {
	friend class ODEKoerperteil;
public:

	/**
	 * 
	 * @param welt 
	 */
	virtual void erzeugeBody(Welt * /*in*/welt) = 0;

	/**
	 * 
	 * @param rotation 
	 */
	virtual void setRotation(double /*in*/rotation) = 0;

	/**
	 * 
	 * @return  
	 */
	virtual void * getBody() = 0;

	/**
	 * 
	 */
	virtual void zeichne() = 0;

	/**
	 * 
	 * @param laenge 
	 */
	void setLaenge(double /*in*/laenge);

	/**
	 * 
	 * @param radius 
	 */
	void setRadius(double /*in*/radius);

	/**
	 * 
	 * @param x 
	 * @param y 
	 * @param z 
	 */
	void setPosition(double /*in*/x, double /*in*/y, double /*in*/z);

private:

	/**
	 * 
	 */
	double radius;

	/**
	 * 
	 */
	double laenge;

	/**
	 * 
	 */
	double position[3];
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Koerperteil class header
 ************************************************************/

#endif
