// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Koerperteil_BODY

/************************************************************
 Koerperteil class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Koerperteil.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @param laenge 
 */
void Koerperteil::setLaenge(double /*in*/laenge) {
	this->laenge = laenge;
}

/**
 * 
 * @param radius 
 */
void Koerperteil::setRadius(double /*in*/radius) {
	this->radius = radius;
}

/**
 * 
 * @param x 
 * @param y 
 * @param z 
 */
void Koerperteil::setPosition(double /*in*/x, double /*in*/y, double /*in*/z) {
	position[0] = x;
	position[1] = y;
	position[2] = z;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Koerperteil class body
 ************************************************************/
