// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Oberschenkelfabrik_BODY

/************************************************************
 Oberschenkelfabrik class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Oberschenkelfabrik.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 *
 * @return
 * @param welt
 * @param seite
 */
ODEKoerperteil * Oberschenkelfabrik::erzeugeKoerper(Welt * /*in*/welt,
		char /*in*/seite) {

	ODEKoerperteil *oberschenkel = new ODEKoerperteil();

	if (seite == 'l') { oberschenkel->setPosition(bein_x, 0, oberschenkel_y); }
	else { oberschenkel->setPosition(-bein_x, 0, oberschenkel_y); }

	oberschenkel->setRadius(0.08);
	oberschenkel->setLaenge(0.5);

	return oberschenkel;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Oberschenkelfabrik class body
 ************************************************************/
