// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROBOTERSIMULATION_NAOSIMULATION_ODEKOERPERTEIL_H
#define ROBOTERSIMULATION_NAOSIMULATION_ODEKOERPERTEIL_H

/************************************************************
 ODEKoerperteil class header
 ************************************************************/

#include "Robotersimulation/Naosimulation/Pkg_Naosimulation.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Robotersimulation/Naosimulation/Koerperteil.h"
#include "Robotersimulation/Pkg_Robotersimulation.h"
#include <ode/ode.h>
#include <drawstuff/drawstuff.h>

namespace Robotersimulation {
namespace Naosimulation {

/************************************************************/
/**
 * 
 */
class ODEKoerperteil: public Koerperteil {
	friend class Koerperteil;
public:

	/**
	 * 
	 * @param rotation 
	 */
	void setRotation(double /*in*/rotation);

	/**
	 * 
	 */
	void zeichne();

	/**
	 * 
	 * @param welt 
	 */
	void erzeugeBody(Welt * /*in*/welt);

	/**
	 * 
	 * @return  
	 */
	void * getBody();

private:

	/**
	 * 
	 */
	dBodyID body;

	/**
	 * 
	 */
	dMatrix3 rotation;

	/**
	 * 
	 */
	dGeomID geom;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of ODEKoerperteil class header
 ************************************************************/

#endif
