// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Simulation_BODY

/************************************************************
 Simulation class body
 ************************************************************/

// include associated header file
#include <Robotersimulation/Naosimulation/ODESimulation.h>

#include <sys/time.h>
#include <iostream>

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)
//Roboter ODESimulation::roboter;
ODEWelt ODESimulation::odewelt;
timeval ODESimulation::start;
timeval ODESimulation::end;
double ODESimulation::zeit;

/**
 * @param argc
 * @param argv
 */
ODESimulation::ODESimulation(int argc, char **argv) : Simulation(argc, argv) {
	drawstuff_vorbereiten();
	dInitODE();

	odewelt.erzeugeWelt();

	roboter.erzeugeRoboter(&odewelt);

	dWorldSetGravity((dWorldID) odewelt.getID(),0,0,0);

	gettimeofday(&start, 0);
}

/**
 *
 */
void ODESimulation::drawstuff_vorbereiten() {
	fn.version = DS_VERSION;
	fn.start   = &starten;
	fn.step    = &simulationschleife_ausfuehren;
	fn.command = &tastatur_auslesen;
	fn.stop    = NULL;
	fn.path_to_textures = "/usr/local/include/drawstuff/textures";
}

/**
 *
 */
void ODESimulation::starten() {
	static float xyz[3] = {0.0,-3.0,1.0};
	static float hpr[3] = {90.0,0.0,0.0};
	dsSetViewpoint (xyz,hpr);
}

/**
 *
 * @param pause 
 */
void ODESimulation::simulationschleife_ausfuehren(int /*in*/pause) {
	odewelt.step();

	roboter.update();
	roboter.zeichne();

	gettimeofday(&end, 0);

	if (zeit != 0 && end.tv_sec - start.tv_sec >= zeit) {
		dsStop();
	}
}

/**
 * @param zeit
 */
int ODESimulation::simulate(double zeit) {

	this->zeit = zeit;

    dsSimulationLoop (argc,argv,352,288,&fn);

	return 0;
}

/**
 *
 */
void ODESimulation::beende() {
	odewelt.zerstoereWelt();

	dCloseODE();
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Simulation class body
 ************************************************************/
