// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROBOTERSIMULATION_NAOSIMULATION_ODESIMULATION_H
#define ROBOTERSIMULATION_NAOSIMULATION_ODESIMULATION_H

/************************************************************
 Simulation class header
 ************************************************************/

#include "Robotersimulation/Naosimulation/Pkg_Naosimulation.h"

#include "AnsiCLibrary/Pkg_AnsiCLibrary.h"
#include "Robotersimulation/Naosimulation/ODEWelt.h"
#include "Robotersimulation/Naosimulation/Roboter.h"
#include "Simulation.h"

namespace Robotersimulation {
namespace ODE {
class dGeomID;
}
}

namespace Robotersimulation {
namespace Naosimulation {

/************************************************************/
/**
 * 
 */
class ODESimulation : public Simulation {

	friend class Simulation;

public:

	/**
	 * 
	 */
	void drawstuff_vorbereiten();

	/**
	 * 
	 */
	static void starten();

	/**
	 * 
	 * @param *data 
	 * @param o1 
	 * @param o2 
	 */
	//static void nearCallback(void /*in*/*data, dGeomID /*in*/o1,
	//		dGeomID /*in*/o2);

	/**
	 * 
	 * @param pause 
	 */
	static void simulationschleife_ausfuehren(int /*in*/pause);

	/**
	 * @param double
	 */
	int simulate(double zeit);

	/**
	 * @param argc
	 * @param **argv
	 */
	ODESimulation(int argc, char **argv);

	/**
	 *
	 */
	void beende();

private:

	/**
	 * 
	 */
	static ODEWelt odewelt;

	/**
	 * 
	 */
	//static dJointGroupID contactgroup;

	/**
	 *
	*/
	static timeval start, end;

	/**
	 *
	*/
	static double zeit;

	/**
	 *
	 */
	dsFunctions fn;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Simulation class header
 ************************************************************/

#endif
