// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_ODEWelt_BODY

/************************************************************
 ODEWelt class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/ODEWelt.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @return  
 */
void * ODEWelt::getID() {
	return weltID;
}

/**
 * 
 */
void ODEWelt::erzeugeWelt() {
	weltID = dWorldCreate();
}

/**
 * 
 */
void ODEWelt::zerstoereWelt() {
	dWorldDestroy((dWorldID) weltID);
}

void ODEWelt::step() {
	dWorldStep((dWorldID) weltID,0.01);
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of ODEWelt class body
 ************************************************************/
