// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROBOTERSIMULATION_NAOSIMULATION_ODEWELT_H
#define ROBOTERSIMULATION_NAOSIMULATION_ODEWELT_H

/************************************************************
 ODEWelt class header
 ************************************************************/

#include "Robotersimulation/Naosimulation/Pkg_Naosimulation.h"

#include "Robotersimulation/Naosimulation/Welt.h"
#include "Robotersimulation/Pkg_Robotersimulation.h"
#include <ode/ode.h>

namespace Robotersimulation {
namespace Naosimulation {

/************************************************************/
/**
 * 
 */
class ODEWelt: public Welt {
public:

	/**
	 * 
	 * @return  
	 */
	void * getID();

	/**
	 * 
	 */
	void erzeugeWelt();

	/**
	 * 
	 */
	void zerstoereWelt();

	/**
	 *
	 */
	void step();

private:

	/**
	 * 
	 */
	dWorldID weltID;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of ODEWelt class header
 ************************************************************/

#endif
