// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Schienbeinfabrik_BODY

/************************************************************
 Schienbeinfabrik class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Schienbeinfabrik.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @return  
 * @param welt 
 * @param seite 
 */
ODEKoerperteil * Schienbeinfabrik::erzeugeKoerper(Welt * /*in*/welt,
		char /*in*/seite) {

	ODEKoerperteil *schienbein = new ODEKoerperteil();

	if (seite == 'l') { schienbein->setPosition(bein_x, 0, 0.55); }
	else { schienbein->setPosition(-bein_x, 0, 0.55); }

	schienbein->setRadius(0.08);
	schienbein->setLaenge(bein_laenge);

	return schienbein;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Schienbeinfabrik class body
 ************************************************************/
