// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Welt_BODY

/************************************************************
 Welt class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Welt.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

}// of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Welt class body
 ************************************************************/
