// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Anklepitchfabrik_BODY

/************************************************************
 Anklepitchfabrik class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Anklepitchfabrik.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @param koerper1 
 * @param koerper2 
 * @param welt 
 * @param seite 
 * @return  
 */
ODEGelenk * Anklepitchfabrik::getGelenk(Koerperteil * /*in*/koerper1,
		Koerperteil * /*in*/koerper2, Welt * /*in*/welt, char /*in*/seite) {

	ODEGelenk *gelenk = new ODEGelenk();

	gelenk->erzeugeGelenk(koerper1, koerper2, welt);

	if (seite == 'l' ) gelenk->setAnker(bein_x, 0, knoechel_y);
	else gelenk->setAnker(-bein_x, 0, knoechel_y);

	gelenk->setAchse(1, 0, 0);
	gelenk->setMinWinkel(-68.15);
	gelenk->setMaxWinkel(52.86);

	return gelenk;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Anklepitchfabrik class body
 ************************************************************/
