// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Gelenkfabrik_BODY

/************************************************************
 Gelenkfabrik class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Gelenkfabrik.h"

// Derived includes directives
#include "Robotersimulation/Naosimulation/Koerperteil.h"
#include "Robotersimulation/Naosimulation/Welt.h"

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @param *koerper1 
 * @param *koerper2 
 * @param *welt 
 * @param seite 
 * @return  
 */
ODEGelenk * Gelenkfabrik::erzeugeGelenk(Koerperteil /*in*/*koerper1,
		Koerperteil /*in*/*koerper2, Welt /*in*/*welt, char /*in*/seite) {

	ODEGelenk* gelenk = new ODEGelenk();

	gelenk = getGelenk(koerper1, koerper2, welt, seite);

	return gelenk;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Gelenkfabrik class body
 ************************************************************/
