// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define Robotersimulation_Naosimulation_Koerperteilfabrik_BODY

/************************************************************
 Koerperteilfabrik class body
 ************************************************************/

// include associated header file
#include "Robotersimulation/Naosimulation/Koerperteilfabrik.h"

// Derived includes directives

namespace Robotersimulation {
namespace Naosimulation {

// static attributes (if any)

/**
 * 
 * @return  
 * @param welt 
 * @param seite 
 */
ODEKoerperteil * Koerperteilfabrik::erzeugeKoerperteil(Welt * /*in*/welt,
		char /*in*/seite) {

	ODEKoerperteil *koerper = new ODEKoerperteil ();
	koerper = erzeugeKoerper(welt, seite);
	koerper->erzeugeBody(welt);

	return koerper;
}

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Koerperteilfabrik class body
 ************************************************************/
