// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef ROBOTERSIMULATION_NAOSIMULATION_WELT_H
#define ROBOTERSIMULATION_NAOSIMULATION_WELT_H

/************************************************************
 Welt class header
 ************************************************************/

#include "Robotersimulation/Naosimulation/Pkg_Naosimulation.h"

#include "Robotersimulation/Pkg_Robotersimulation.h"

namespace Robotersimulation {
namespace Naosimulation {

/************************************************************/
/**
 * 
 */
class Welt {
public:

	/**
	 * 
	 */
	virtual void erzeugeWelt() = 0;

	/**
	 * 
	 */
	virtual void zerstoereWelt() = 0;

	/**
	 * 
	 * @return  
	 */
	virtual void * getID() = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace Naosimulation
} // of namespace Robotersimulation

/************************************************************
 End of Welt class header
 ************************************************************/

#endif
